"""Initial migration with robot_state, command_history, and obstacles tables

Revision ID: 1aa54a9deae0
Revises:
Create Date: 2025-08-04 10:32:41.820898

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "1aa54a9deae0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column("position_x", sa.Integer(), nullable=True),
        sa.Column("position_y", sa.Integer(), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=True),
        sa.Column("obstacle_detected", sa.Boolean(), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_history_id"), "command_history", ["id"], unique=False
    )
    op.create_table(
        "obstacles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_x", sa.Integer(), nullable=False),
        sa.Column("position_y", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("position_x", "position_y", name="uq_obstacle_position"),
    )
    op.create_index(op.f("ix_obstacles_id"), "obstacles", ["id"], unique=False)
    op.create_table(
        "robot_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_x", sa.Integer(), nullable=False),
        sa.Column("position_y", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_robot_state_id"), "robot_state", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_robot_state_id"), table_name="robot_state")
    op.drop_table("robot_state")
    op.drop_index(op.f("ix_obstacles_id"), table_name="obstacles")
    op.drop_table("obstacles")
    op.drop_index(op.f("ix_command_history_id"), table_name="command_history")
    op.drop_table("command_history")
    # ### end Alembic commands ###
