"""Update default direction value for robot_state table

Revision ID: 59ae276bf76e
Revises: 1aa54a9deae0
Create Date: 2025-08-05 00:27:06.696639

"""

from collections.abc import Sequence

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "59ae276bf76e"
down_revision: str | Sequence[str] | None = "1aa54a9deae0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("robot_state", "direction", server_default="NORTH")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("robot_state", "direction", server_default=None)
    # ### end Alembic commands ###
